import Head from "next/head";
import React, { useState } from "react";
import Header from '@/components/Header';
import Banner from "@/components/Banner";
import Footer from "@/components/Footer";
import ExpWork from "@/components/ExpWork";
import Info from "@/components/Info";
import Form from "@/components/Form";
import { useState } from "react";

export default function Home() {
<<<<<<< HEAD
  const [theme, setTheme] = useState(false);

  const handleChangeTheme = () => {
    setTheme(!theme);
    console.log(theme)
  };
=======
  const [theme, setTheme] = useState(false)


>>>>>>> 0d66051ee844093e200895ad4b7fa2f0ed9fd02c
  return (
    <>
      <Head>
        <title>Twilight - Agência Design Digital</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
        <link href="https://fonts.googleapis.com/css2?family=Montserrat:ital,wght@0,100..900;1,100..900&display=swap" rel="stylesheet" />
        <link rel="icon" href="/assets/logo.png" />
      </Head>
      <Header theme={theme} changeTheme={handleChangeTheme} />
      <main>
        <Banner />
        <Info />
        <ExpWork theme={theme} />
        <Form />
      </main>
      <Footer theme={theme} />

    </>
  );
}
