import Head from "next/head";
import Image from "next/image";
import styles from "@/styles/Home.module.css";

import Header from '@/components/Header';
import Banner from "@/components/Banner";
import Footer from "@/components/Footer";
import ExpWork from "@/components/ExpWork";
import Info from "@/components/Info";
import Form from "@/components/Form";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
        <link href="https://fonts.googleapis.com/css2?family=Montserrat:ital,wght@0,100..900;1,100..900&display=swap" rel="stylesheet" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <main>
        <Banner />
        <Info />
        <ExpWork />
        <Form />
      </main>
      <Footer />

    </>
  );
}
